// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VizsgaremekBackend.Data;

#nullable disable

namespace VizsgaremekBackend.Migrations
{
    [DbContext(typeof(VizsgaremekContext))]
    [Migration("20260922100147_AddRelations")]
    partial class AddRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VizsgaremekBackend.Models.Kolcsonzes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expirationdate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<Guid>("PeldanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("peldanyid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_kolcsonzess");

                    b.HasIndex("PeldanyId")
                        .HasDatabaseName("ix_kolcsonzess_peldanyid");

                    b.ToTable("kolcsonzess", (string)null);
                });

            modelBuilder.Entity("VizsgaremekBackend.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("VizsgaremekBackend.Models.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_logs_userid");

                    b.ToTable("logs", (string)null);
                });

            modelBuilder.Entity("VizsgaremekBackend.Models.Peldany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("adddate");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("FelelosId")
                        .HasColumnType("uuid")
                        .HasColumnName("felelosid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("locationid");

                    b.Property<DateTime?>("ManufacturingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("manufacturingdate");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parentid");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("typeid");

                    b.HasKey("Id")
                        .HasName("pk_peldanys");

                    b.HasIndex("FelelosId")
                        .HasDatabaseName("ix_peldanys_felelosid");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_peldanys_locationid");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_peldanys_parentid");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_peldanys_typeid");

                    b.ToTable("peldanys", (string)null);
                });

            modelBuilder.Entity("VizsgaremekBackend.Models.Type", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_types");

                    b.ToTable("types", (string)null);
                });

            modelBuilder.Entity("VizsgaremekBackend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeviceAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeviceadmin");

                    b.Property<bool>("IsSysAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("issysadmin");

                    b.Property<bool>("IsUserAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("isuseradmin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("VizsgaremekBackend.Models.Kolcsonzes", b =>
                {
                    b.HasOne("VizsgaremekBackend.Models.Peldany", "Peldany")
                        .WithMany("Kolcsonzeses")
                        .HasForeignKey("PeldanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kolcsonzess_peldanys_peldanyid");

                    b.Navigation("Peldany");
                });

            modelBuilder.Entity("VizsgaremekBackend.Models.Log", b =>
                {
                    b.HasOne("VizsgaremekBackend.Models.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_logs_users_userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VizsgaremekBackend.Models.Peldany", b =>
                {
                    b.HasOne("VizsgaremekBackend.Models.User", "FelelosUser")
                        .WithMany("Peldanys")
                        .HasForeignKey("FelelosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_peldanys_users_felelosid");

                    b.HasOne("VizsgaremekBackend.Models.Location", "Location")
                        .WithMany("Peldanys")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_peldanys_locations_locationid");

                    b.HasOne("VizsgaremekBackend.Models.Peldany", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_peldanys_peldanys_parentid");

                    b.HasOne("VizsgaremekBackend.Models.Type", "Type")
                        .WithMany("Peldanys")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_peldanys_types_typeid");

                    b.Navigation("FelelosUser");

                    b.Navigation("Location");

                    b.Navigation("Parent");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("VizsgaremekBackend.Models.Location", b =>
                {
                    b.Navigation("Peldanys");
                });

            modelBuilder.Entity("VizsgaremekBackend.Models.Peldany", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Kolcsonzeses");
                });

            modelBuilder.Entity("VizsgaremekBackend.Models.Type", b =>
                {
                    b.Navigation("Peldanys");
                });

            modelBuilder.Entity("VizsgaremekBackend.Models.User", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Peldanys");
                });
#pragma warning restore 612, 618
        }
    }
}
